{% set name = "pybsm" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybsm-{{ version }}.tar.gz
  sha256: b25b917ceff730cc00eb97015a0f3e29ed057149d08361b08bcb3497db2e2c99

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<2.0
    - matplotlib-base >=3.5.2
    - scipy >=1.10.0,<1.14

test:
  imports:
    - pybsm
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: pybsm

  - name: pybsm-graphics
    requirements:
      host:
        - python
      run:
        - python
        - py-opencv >=4.6.0
        - {{ pin_subpackage('pybsm', exact=True) }}
    test:
      imports:
        - pybsm
      commands:
        - pip check
      requires:
        - pip

  - name: pybsm-headless
    requirements:
      host:
        - python
      run:
        - python
        - opencv >=4.6.0
        - {{ pin_subpackage('pybsm', exact=True) }}
    test:
      imports:
        - pybsm
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://pypi.org/project/pybsm/
  summary: 'This repo builds off of the work done by LeMaster and Eismann in creating the original pyBSM package for modeling image systems as well as LeMaster, et al. in their work in validating the pyBSM package'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eveenhuis
    - bjrichardwebster
    - barry-ravichandran
    - Purg
