{% set name = "pybsm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybsm-{{ version }}.tar.gz
  sha256: 87df801e7959fff290a39966d989217ef04d6b20cc9afa95d827e594320e0a61

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.23.1,<1.25  # [py<312]
    - numpy >=1.25  # [py>=312]
    - matplotlib-base >=3.5.2,<4.0.0
    - scipy >=1.8.1,<1.9  # [py<311]
    - scipy >=1.9  # [py>=311]
    - py-opencv >=4.6.0,<5.0.0

test:
  imports:
    - pybsm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pybsm/
  summary: 'This repo builds off of the work done by LeMaster and Eismann in creating the original pyBSM package for modeling image systems as well as LeMaster, et al. in their work in validating the pyBSM package'
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bjrichardwebster
    - barry-ravichandran
    - Purg
